# Generated by Django 5.2.3 on 2025-07-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_claim"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="contents_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="last_seen_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="claim",
            name="proof",
            field=models.ImageField(blank=True, null=True, upload_to="claim_proofs/"),
        ),
        migrations.AddField(
            model_name="claim",
            name="unique_marking",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
